In [1]:
import pandas as pd
import numpy as np

In [3]:
csv_file = "BEA_data.csv"
BEA_df = pd.read_csv(csv_file, encoding='latin-1')
BEA_df.head()

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,1969,1970,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,"""00000""",United States,,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,791229000,855525000,...,13330436000,14003346000,14189228000,14969527000,15681233000,16092713000,16845028000,17681159000,18402004000,19607447000
1,"""00000""",United States,,CAINC1,2.0,...,Population (persons) 1/,Number of persons,201298000,203798722,...,311583481,313877662,316059947,318386329,320738994,323071755,325122128,326838199,328329953,329484123
2,"""00000""",United States,,CAINC1,3.0,...,Per capita personal income (dollars) 2/,Dollars,3931,4198,...,42783,44614,44894,47017,48891,49812,51811,54098,56047,59510
3,"""01000""",Alabama,5,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,9737715,10628318,...,168474324,173361655,175185262,181078773,189115437,192363456,199336413,207053583,215930375,228748804
4,"""01000""",Alabama,5,CAINC1,2.0,...,Population (persons) 1/,Number of persons,3440000,3449846,...,4799642,4816632,4831586,4843737,4854803,4866824,4877989,4891628,4907965,4921532

In [5]:
reduced_BEA_df = BEA_df[["GeoFIPS", "GeoName", "Region", "TableName", "LineCode", "IndustryClassification", "Description", "Unit", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" ]]
reduced_BEA_df

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,2013,2014,2015,2016,2017,2018,2019,2020
0,"""00000""",United States,,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,14189228000,14969527000,15681233000,16092713000,16845028000,17681159000,18402004000,19607447000
1,"""00000""",United States,,CAINC1,2.0,...,Population (persons) 1/,Number of persons,316059947,318386329,320738994,323071755,325122128,326838199,328329953,329484123
2,"""00000""",United States,,CAINC1,3.0,...,Per capita personal income (dollars) 2/,Dollars,44894,47017,48891,49812,51811,54098,56047,59510
3,"""01000""",Alabama,5,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,175185262,181078773,189115437,192363456,199336413,207053583,215930375,228748804
4,"""01000""",Alabama,5,CAINC1,2.0,...,Population (persons) 1/,Number of persons,4831586,4843737,4854803,4866824,4877989,4891628,4907965,4921532
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9599,"""98000""",Far West,8,CAINC1,3.0,...,Per capita personal income (dollars) 2/,Dollars,47320,50056,53065,54895,57115,59774,62434,67447
9600,Note: See the included footnote file.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9601,CAINC1: Personal Income Summary: Personal Inco...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9602,"Last updated: November 16, 2021-- new statisti...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9603,Source: U.S. Department of Commerce / Bureau o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
reduced_BEA_df.to_csv('BEA_2013_2020.csv', encoding='utf-8', index=False)